export const backgroundColor = "#ffffff";
export const activeColor = "rgba(250, 250, 50, 1)";
export const hoverColor = "rgba(250, 250, 50, 0.3)";
export const borderColor = "#dddddd";
export const activeBorderColor = "#ffffff";
export const transparentColor = "transparent";
export const buttonBackgroundColor = "rgba(140, 140, 140, 0.1)";
export const winColor = "green";
export const loseColor = "red";
